### ISSUE TITLE
Problems with collaboration...

### ISSUE THREAD

**Issue by Angelfirenze01** [deadlyvipers/dojo_rules#12528]
I am not receiving the new_rules branch. I can't seem to get it added to my repository. I added @codeschool-kiddo as a collaborator, but the Deadly Skills list was the last thing I was asked to do.

Why have I not received a response about this problem?  I want to be able to continue with the project past this point.  Is @codeschool-kiddo an automated account?  If so, then you'd need to set up dependencies for certain actions on the client-side, but it also means that when the client-side fulfills what is asked of them, the server-side is supposed to react accordingly, correct?

May I please ask what's going on with this project?  I keep getting stuck in completely random places for reasons that seem to be happening server-side.  I really like and want to finish this project.

Could it be something _I'm_ not doing properly, if so, please tell me what it is.

**Comment by klbjlabs** [comment]
granting Mastering Github access
![image](https://cloud.githubusercontent.com/assets/4111893/21083055/0c149c86-c023-11e6-8776-c17ecf0f3c3d.png)
same problems

**Comment by blackeye68** [comment]
same porblems

**Comment by Angelfirenze01** [comment]
These problems are no longer under Code School, they're now in the possession of Pluralsight, though they are porting over Code Schoo paidl accounts.
