### ISSUE TITLE
Code School Kiddo awaiting response

### ISSUE THREAD

**Issue by Asjas** [deadlyvipers/dojo_rules#15590]
I'm trying to add the Code School Kiddo as a collaborator but it's not working. I've removed access and requested access more than 8 times and it's still just waiting for a response. Is there a problem with it being overloaded?

**Comment by diegoflassa** [comment]
Same problem here

**Comment by Asjas** [comment]
I think the free weekend might have broken it. And it's sad because I want to finish this course before the free weekend is over else I'll have to pay for a month just to finish this one course.

**Comment by diegoflassa** [comment]
Hy! Change the username to "karlyn33" ( in the "GitHub Username" ) and the course will validate the task ( you can change back to yours later )

**Comment by diegoflassa** [comment]
It is not the best way, but at least we will be able to continue :-)

**Comment by Asjas** [comment]
@diegoflassa Thanks dude. Free weekend continues :100:

**Comment by diegoflassa** [comment]
For 2.4 use the user "nounweb"

**Comment by diegoflassa** [comment]
For 3.6, use ERR0000RR
